### ISSUE TITLE
Links broken from adamgreenhall.com/power-blog/

### ISSUE THREAD

**Issue by hazeledmands** [adamgreenhall/power-blog#1]
Hi! I wasn't sure how else to get in touch - but I'm excited about your power blog, after seeing a link to it from Amelia's web site!

I also wanted to let you know that the links to individual articles appear to be broken from https://adamgreenhall.com/power-blog/, though they work from the homepage https://adamgreenhall.com/.

**Comment by adamgreenhall** [comment]
Thank you! Fixed now
